apis:
  - terraform/infrastructure/apis/**

firebase-project:
  - terraform/infrastructure/firebase-project/**

k8s-network:
  - terraform/infrastructure/k8s/network/**
  - terraform/modules/network/**
  - terraform/modules/nat/**
  - terraform/modules/subnet/**

k8s-cluster:
  - terraform/infrastructure/k8s/cluster/**
  - terraform/modules/k8s/cluster/**
  - terraform/modules/k8s/node-pool/**

k8s-node-pool:
  - terraform/infrastructure/k8s/nodes/**
  - terraform/modules/k8s/node-pool/**

sql:
  - terraform/infrastructure/sql/**
  - terraform/modules/sql/**
