apis:
  - terraform/infrastructure/apis/**

firebase-project:
  - terraform/infrastructure/firebase-project/**

k8s-network:
  - terraform/infrastructure/k8s/network/**
  - terraform/modules/network/**
  - terraform/modules/nat/**
  - terraform/modules/subnet/**
