apis:
  - terraform/infrastructure/apis/**

firebase-project:
  - terraform/infrastructure/firebase-project/**

k8s-network:
  - terraform/infrastructure/k8s/network/**
  - terraform/modules/network/**
  - terraform/modules/nat/**
  - terraform/modules/subnet/**

k8s-cluster:
  - terraform/infrastructure/k8s/cluster/**
  - terraform/modules/k8s/cluster/**
  - terraform/modules/k8s/node-pool/**
  - terraform/modules/service-accounts/**

k8s-node-pool:
  - terraform/infrastructure/k8s/nodes/**
  - terraform/modules/k8s/node-pool/**
  - terraform/modules/service-accounts/**

sql:
  - terraform/infrastructure/sql/**
  - terraform/modules/sql/**

vuevideo-backend:
  - k8s/server/**

vuevideo-frontend:
  - k8s/client/**

network-policy:
  - k8s/network-policy/**
