apiVersion: v1
kind: Service

metadata:
  name: client-service
  namespace: vuevideo
  labels:
    app: vuevideo
    component: client

spec:
  type: LoadBalancer
  selector:
    app: vuevideo
    component: client

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
