apiVersion: apps/v1

kind: Deployment

metadata:
  name: server-deployment
  namespace: vuevideo
  labels:
    app: vuevideo
    component: server

spec:
  replicas: 3
  selector:
    matchLabels:
      app: vuevideo
      component: server

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2

  template:
    metadata:
      labels:
        app: vuevideo
        component: server

    spec:
      containers:
        - name: server
          image: docker.io/vuevideo/server:SERVER_VERSION
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: firebase-sa
              mountPath: /secrets/
              readOnly: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"

        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          args:
            - "--structured-logs"
            - "--port=5432"
            - "<INSTANCE_CONNECTION_NAME>"
            - "--credentials-file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: sql-sa
              mountPath: /secrets/
              readOnly: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"

      volumes:
        - name: firebase-sa
          secret:
            secretName: firebase-sa
        - name: sql-sa
          secret:
            secretName: sql-sa
