apiVersion: v1
kind: Service

metadata:
  name: server-service
  namespace: vuevideo
  labels:
    app: vuevideo
    component: server

spec:
  type: ClusterIP
  selector:
    app: vuevideo
    component: server

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
