name: Deploy Infrastructure using Terraform

on:
  push:
    branches:
      - feature/*/*
      - release/*
  workflow_dispatch:

jobs:
  prerequisites:
    name: Pipeline Prequisites
    uses: ./.github/workflows/prerequisites.reusable.yml

  apis:
    name: APIs to enable
    needs: [prerequisites]
    if: ${{ contains(fromJSON(needs.prerequisites.outputs.jobs), 'apis') }}
    uses: ./.github/workflows/tf.reusable.yml
    with:
      environment: ${{ needs.prerequisites.outputs.environment }}
      infrastructure_path: terraform/infrastructure/apis

  firebase-project:
    name: Create Firebase Project
    needs: [prerequisites]
    if: ${{ contains(fromJSON(needs.prerequisites.outputs.jobs), 'firebase-project') }}
    uses: ./.github/workflows/tf.reusable.yml
    with:
      environment: ${{ needs.prerequisites.outputs.environment }}
      infrastructure_path: terraform/infrastructure/firebase-project
