name: Deploy Infrastructure using Terraform

on:
  push:
    branches:
      - feature/*/*
      - release/*
  workflow_dispatch:

jobs:
  prerequisites:
    name: Pipeline Prequisites
    uses: ./.github/workflows/prerequisites.reusable.yml

  apis:
    name: APIs to enable
    needs: [prerequisites]
    if: |
      contains(fromJSON(needs.prerequisites.outputs.jobs), 'apis') && !(cancelled() || failure())
    uses: ./.github/workflows/tf.reusable.yml
    with:
      environment: ${{ needs.prerequisites.outputs.environment }}
      infrastructure_path: terraform/infrastructure/apis

  firebase-project:
    name: Create Firebase Project
    needs: [prerequisites, apis]
    if: |
      contains(fromJSON(needs.prerequisites.outputs.jobs), 'firebase-project') && !(cancelled() || failure())
    uses: ./.github/workflows/tf.reusable.yml
    with:
      environment: ${{ needs.prerequisites.outputs.environment }}
      infrastructure_path: terraform/infrastructure/firebase-project

  k8s-network:
    name: Kubernetes Network Creation
    needs: [prerequisites, firebase-project]
    if: |
      contains(fromJSON(needs.prerequisites.outputs.jobs), 'k8s-network') && !(cancelled() || failure())
    uses: ./.github/workflows/tf.reusable.yml
    with:
      environment: ${{ needs.prerequisites.outputs.environment }}
      infrastructure_path: terraform/infrastructure/k8s/network

  k8s-cluster-and-node-pool:
    name: Kubernetes Cluster and Node Pool Creation
    needs: [prerequisites, k8s-network]
    if: |
      contains(fromJSON(needs.prerequisites.outputs.jobs), 'k8s-cluster-and-node-pool') && !(cancelled() || failure())
    uses: ./.github/workflows/tf.reusable.yml
    with:
      environment: ${{ needs.prerequisites.outputs.environment }}
      infrastructure_path: terraform/infrastructure/k8s/cluster

  sql:
    name: Cloud SQL Server Creation
    needs: [prerequisites, k8s-network]
    if: |
      contains(fromJSON(needs.prerequisites.outputs.jobs), 'sql') && !(cancelled() || failure())
    uses: ./.github/workflows/tf.reusable.yml
    with:
      environment: ${{ needs.prerequisites.outputs.environment }}
      infrastructure_path: terraform/infrastructure/sql
