name: Deploy Workload Identity Pool and Provider

on:
  workflow_dispatch:
    inputs:
      environment:
        default: dev
        required: true
        description: Environment to deploy Workload Identity Pool and Provider in
        type: environment

  push:

jobs:
  wif_apply:
    name: Deploy Workload Identity Pool and Provider
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: terraform/infrastructure/workload-identity
    # steps:
    #   - name: Checkout Repository
    #     uses: actions/checkout@v3

    #   - name: Setup Terraform
    #     uses: hashicorp/setup-terraform@v2
    #     with:
    #       terraform_version: '1.3.3'

    #   - name: Authenticating with GCP
    #     uses: 'google-github-actions/auth@v1'
    #     with:
    #       credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    #   - name: Set up Cloud SDK
    #     uses: 'google-github-actions/setup-gcloud@v1'
    #     with:
    #       install_components: 'gsutil'

    #   - name: Copy required TFVars File from GCS Bucket
    #     run: gsutil cp "${{ vars.TERRAFORM_TFVARS_PATH }}" terraform.tfvars

    #   - name: Terraform Initialization
    #     id: init
    #     run: terraform init --backend-config="bucket=${{ vars.TERRAFORM_BACKEND }}"

    #   - name: Running Terraform Plan
    #     id: plan
    #     run: terraform plan

    #   - name: Deploying resources
    #     run: terraform apply -auto-approve

